### ISSUE TITLE
Publish the change to the 0.3.0 SDK Core ??

### ISSUE THREAD

**Issue by ncancelliere** [paypal/permissions-sdk-ruby#5]
Are you planning on publishing the dependency change so that bundler doesn't freak out?  You updated the SDK core dependency in the project, but never published it under a new version on Rubygems.

https://rubygems.org/gems/paypal-sdk-permissions

**Comment by juwlee** [comment]
@ncancelliere we will update this SDK if there is any API change along with it. Can you be more specific about "bundler freaking out?" Do you get an error? Updates since 0.2.3 version of core are mostly for REST SDK.

**Comment by ncancelliere** [comment]
You have bumped the gemspec dependency for PayPal SDK Code but you haven't pushed this out to RubyGems. This makes is difficult to bundle the permissions-sdk library with any of your other gems that have updated their gems on Rubygems.org because of the contflict between the PayPal SDK gem (when you try to bundle).  I am asking simply that you publish your change. Thanks.

**Comment by juwlee** [comment]
@ncancelliere thanks for clarifying. [A new version](https://rubygems.org/gems/paypal-sdk-permissions/versions/1.96.4) has been released.
