### ISSUE TITLE
Getting Error in SetExpressCheckout Action

### ISSUE THREAD

**Issue by Sivan1525** [paypal/permissions-sdk-ruby#6]
Hello,

I am sending you the latest error,I am getting when I am setting grant permission on my profile on sharetribe.Here is the error,please check and let me know.

Request : Request[post]: https://api-3t.paypal.com/2.0/
Response : [Paypal] paypal response: {"ebl:Timestamp":"2015-04-13T16:17:13+00:00","ebl:Ack":"Failure","ebl:CorrelationID":"6ca7d822f0747","ebl:Errors":[{"ebl:ShortMessage":"Channel not enabled for channel initiated billing.","ebl:LongMessage":"Channel not enabled for channel initiated billing.","ebl:ErrorCode":"13200","ebl:SeverityCode":"Error"}],"ebl:Version":"116.0","ebl:Build":"16204765"}

Please check it and let me know.It is very urgent.

Thanks.

**Comment by juwlee** [comment]
@Sivan1525 it looks like an account issue. To be specific,  the channel does not seem to be enabled for billing. Please reach out to PayPal MTS, as it looks like an account issue.

**Comment by svallory** [comment]
Hey @Sivan1525, did you manage to solve this issue?

**Comment by juwlee** [comment]
@svallory I would suggest that you reach out to [PP MTS](https://ppmts.custhelp.com/app/answers/list) with the error response.

**Comment by svallory** [comment]
Thanks @juwlee! But I figured it out..

The software I was using (in this case sharetribe) has a special (and undocumented) L_BILLINGTYPE available to them: "ChannelInitiatedBilling". So I changed it to "MerchantInitiatedBillingSingleAgreement", as per [SetExpressCheckout_API_Operation_NVP](https://developer.paypal.com/docs/classic/api/merchant/SetExpressCheckout_API_Operation_NVP) and it worked :)

**Comment by juwlee** [comment]
@svallory glad it worked! :)
