### ISSUE TITLE
Issue requesting basic personal data

### ISSUE THREAD

**Issue by rjlynch** [paypal/permissions-sdk-ruby#8]
### General information

* SDK/Library version: "1.96.4"
* Environment: Sandbox
* `PayPal-Debug-ID` values: See below
* Language, language version, and OS: Ruby, 2.3.0, Ubuntu 16.04

### Issue description

Hi
I'm having issues when trying to get basic personal data.
The SDK allows me to authenticate/request permissions fine (and this allows me to get transaction history etc via curl)
However the following code:
```ruby
    # params request_token and verification_code come from the paypal callback.
    api = PayPal::SDK::Permissions::API.new({
       token: params[:request_token],
       token_secret: params[:verification_code] 
    })
    resp = api.get_basic_personal_data({
      :attributeList => {
        :attribute => [ "http://axschema.org/namePerson/first"]}})
```
Returns an error response:
#<PayPal::SDK::Permissions::DataTypes::GetBasicPersonalDataResponse:0x0000001014d308
 @error=
  [#<PayPal::SDK::Permissions::DataTypes::ErrorData:0x0000001014c908
    @category="Application",
    @domain="PLATFORM",
    @errorId=520002,
    @message="Internal Error",
    @severity="Error",
    @subdomain="Application">],
 @responseEnvelope=
  #<PayPal::SDK::Permissions::DataTypes::ResponseEnvelope:0x0000001014d290
   @ack="Failure",
   @build="2210301",
   @correlationId="f9dd3142eaa19",
   @timestamp=Fri, 14 Jul 2017 07:27:27 -0700>>

This is probably a mistake on my end, but I can't workout what!
Any help is much appreciated.
Thanks,
Rich

**Comment by andreaslillebo** [comment]
Hi

I ran into the same problem. It appears that the sample code in the readme is incomplete.

You are trying to use the `request_token` as the `token` and the `verification_code` as the `token_secret`.

You need to exchange the `request_token` and `verification_code` for `token` and `token_secret`.

In the controller of the `return_url`:

```ruby
# Build request to exchange tokens
@request_access_token = @api.build_get_access_token(
  token: params['request_token'],
  verifier: params['verification_code']
)

# Make API call & get response
@access_token_response = @api.get_access_token(@request_access_token)

# Access Token Response
if @access_token_response.success?
  @token = @access_token_response.token
  @token_secret = @access_token_response.token_secret
else
  @access_token_response.error
end
```

Now you can use `@token` and `@token_secret` to make requests:

```ruby
# params request_token and verification_code come from the paypal callback.
api = PayPal::SDK::Permissions::API.new({
   token: @token,
   token_secret: @token_secret
})
resp = api.get_basic_personal_data({
  :attributeList => {
    :attribute => [ "http://axschema.org/namePerson/first"]}})
```

**Comment by xiaoleih41** [comment]
Can you please submit a pull request and we will review it.

**Comment by andreaslillebo** [comment]
I've just submitted a pull request clarifying the example in the readme. Please let me know if you need me to change anything.
